// <auto-generated />
namespace Todo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedTaskModelfieldtomakerequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedTaskModelfieldtomakerequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202406101525477_updated TaskModel field to make required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
